openapi: 3.0.0
info:
  title: learn express and swagger - LearnCodeOnline
  description: LCO - a course segment about writing docs
  version: 1.1.0
  contact:
   email: manish.info2020@gmail.com
   url: "manishgupta.netlify.app"

# servers:
#  - url: "https://localhost:4000/api/v1"
#    description: for local host - secure
#  - url: "https://localhost:4000/api/v1"
#    description: for local host - regular

servers:
 - url: "{protocol}://localhost:4000/api/{version}"
   description: for local host - secure
   variables:
    version:
     enum:
       - v1
       - v2
    protocol:
     enum:
       - http
       - https